name: pipeline

on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      -
        name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.7
      -
        name: Build with Gradle
        run: ./gradlew build -PprojectVersion=${{ steps.set_version.outputs.safe_version }}
      -
        name: Publish with Gradle
        run: |
          export PUBLISH_USER=${{ secrets.PUBLISH_USER }}
          export PUBLISH_TOKEN=${{ secrets.PUBLISH_TOKEN }}
          ./gradlew publish -PprojectVersion=${{ steps.set_version.outputs.safe_version }}

      -
        name: Print image version
        run: echo ${{ steps.set_version.outputs.safe_version }}